# Use a base image with Java 17 and Gradle
FROM eclipse-temurin:17-jdk-jammy AS builder

# Set the working directory
WORKDIR /app

# Copy the Gradle files and dependencies to leverage caching
COPY build.gradle .
COPY settings.gradle .
COPY gradle ./gradle

# Download the dependencies
# RUN ./gradlew --version

# Copy the application source code
COPY src ./src

# Build the application
RUN ./gradlew build --no-daemon

# Use a lightweight base image for the application
FROM eclipse-temurin:17-jdk-jammy

# Set the working directory
WORKDIR /app

# Copy the JAR file from the builder stage
COPY --from=builder /app/build/libs/textractpoc*.jar app.jar

# Expose the application port
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar","org.springframework.boot.loader.JarLauncher"]
