# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build And Deploy
on:
  push:
    branches:   [main]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Print concurrency group
      run: echo '${{ github.workflow }}-${{ github.ref }}'
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: docker/Dockerfile
                - name: Build and push
                uses: docker/build-push-action@v3
                with:
                  context: .
                  file: docker/Dockerfile
                  tags: |
                    textractpoc:latest
                    textractpoc:${{ needs.get-version.outputs.version}}
                    textractpoc:${{ needs.get-version.outputs.sha_short}}
                  outputs: type=docker,dest=/tmp/textractpoc.tar

        outputs: type=docker,dest=/tmp/textractpoc.tar
        
  deploy-docker-dev:
    if: github.ref == 'refs/heads/main'
    needs: [ Build ]
    uses: ./.github/workflows/deploy_docker.yml
    with:
      version_label: ${{ needs.get-version.outputs.version }}_${{ needs.get-version.outputs.sha_short }}
      environment: dev
    secrets: inherit
